app:
  listen_addr: ':8080'
  data_file: '/tmp/mysql-tarantool/state.info'
  health:
    seconds_behind_master: 10
  logging:
    level: 'debug'
    syslog_enabled: false
    file_enabled: false
    file_name: '/var/log/mysql-tarantool-replicator.log'
    file_max_size: 256
    file_max_backups: 3
    file_max_age: 5

replication:
  server_id: 100
  gtid_mode: true

  mysql:
    dump:
      exec_path: '/usr/bin/mysqldump'
      skip_master_data: false
      extra_options:
        - '--column-statistics=0'
    addr: '127.0.0.1:13306'
    user: 'repl'
    password: 'repl'
    charset: 'utf8'

  tarantool:
    addr: '127.0.0.1:13301'
    user: 'repl'
    password: 'repl'
    max_retries: 3
    connect_timeout: '500ms'
    request_timeout: '500ms'

  mappings:
    - source:
        schema: 'city'
        table: 'users'
        columns:
          - username
          - password
          - email
      dest:
        space: 'users'
        column:
          email:
            on_null: 'stub@mail.ru'
